### ISSUE TITLE
Admin puolella nakkien järjestely.

### ISSUE THREAD

**Issue by haivala** [EntropyRy/nakkikone#10]
olis mahtavaa jos tätä vois tehä.
quickfix: voishan tuon ei admin puolen tietty laittaa järjestämään nuo nakit aakkosjärjestykseen tms.

**Comment by d4gg4d** [comment]
Tämä ratkesi samalla kuin tuo saman tyyppisten nakkien feature, https://github.com/EntropyRy/nakkikone/issues/31 . Eli nyt nakit näkyy samassa järjestyksessä kun ne luodaan admin puolella, mikä on jotenkin loogista.
