### ISSUE TITLE
Design muutos: Nakkien ottamisesta 3-4. vaiheinen prosessi

### ISSUE THREAD

**Issue by haivala** [EntropyRy/nakkikone#19]
1. annetaan informaatiota itse bileistä nakki-infosta
2. valitset  taulukosta 2 nakkia joista kaikista on kuvakset samalla sivulla
3. valitset joko purku tai kasaus nakin ja ymmärrätä mitä se tarkoittaa.
4. yhteenveto: hyväksyt nakit ja sulle kerrotaa milloin sun pitää olla vähintaan paikalla itse bileissä

olisko hyvä?

**Comment by d4gg4d** [comment]
Tämä uudistus on jo sen verran iso, että seuraava nakkikoneen kirjoittaja voi ottaa tästä mallia.

**Comment by haivala** [comment]
niin. tää ei vältisti ole enää mitenkään edes järkevä. 
eikä se välttämättä tuo edes käytettävyyttä lisää, koska kaikki on menny jo nyt aika uusiks
