### ISSUE TITLE
Vaihda alert dialogit bootstrap dialogeiksi

### ISSUE THREAD

**Issue by d4gg4d** [EntropyRy/nakkikone#20]
alertit ovat rumia, tulisi vaihtaa teeman mukaisiksi bootstrap dialogeiksi

**Comment by haivala** [comment]
eikös tää oo jo tehty?

**Comment by d4gg4d** [comment]
nope

**Comment by d4gg4d** [comment]
https://github.com/EntropyRy/nakkikone/releases/tag/2.7.1
