### ISSUE TITLE
Etusivun login

### ISSUE THREAD

**Issue by haivala** [EntropyRy/nakkikone#22]
Uncaught TypeError: Cannot read property 'replace' of undefined nakkikone.entropy.fi/assets/require-handlebars-plugin/Handlebars.js:1711
Uncaught Error: Load timeout for modules: hbs!templates/nakki-table_unnormalized20,hbs!templates/nakki-table
http://requirejs.org/docs/errors.html#timeout require.js:161

**Comment by d4gg4d** [comment]
jostain syystä ollut super hitaalla ja require on aikakatkaissut moduuli latauksen (eivät ole bundlattu yhdeksi filuksi koska, https://github.com/EntropyRy/nakkikone/issues/25)
