### ISSUE TITLE
Party description kentässä olis kiva olla joku WYSIWYG editori

### ISSUE THREAD

**Issue by haivala** [EntropyRy/nakkikone#26]
ckeditor?

**Comment by d4gg4d** [comment]
Vois kokeilla. Sen wysiwyg in pitäisi myös validoida se hötömölö, jotta käyttäjä ei vahingossa luo rikkinäistä materiaalia. Mietin että pitäisikö myös validointi olla renderöinnissä, halutaanko miten pommin varma tästä tehdä.

**Comment by haivala** [comment]
no siis joku joka ei osaa html voi haluta katsoa/editoida tuotostaan wysiwygissa siis siinä itse editorissa oikein mutta se näytetään adminissa raakana (savetuksen jälkeen) ja frontissa aina kuin wysiwygissä?

**Comment by d4gg4d** [comment]
https://github.com/EntropyRy/nakkikone/releases/tag/2.6
