### ISSUE TITLE
Uusi nakki ei ilmesty valittavien listaan

### ISSUE THREAD

**Issue by haivala** [EntropyRy/nakkikone#28]
Eli jos on painanut että edit nakkitable ja sitten huomaa että siellä ei olekkaan nakki infoa mitä haluaisi niin luonnollisesti semmoisen menee sitten tekemään. Kun sen on luonut niin sitä ei ole listassa valittavissa ennen kuin on painanut update nakkitable..

**Comment by d4gg4d** [comment]
Pitää katsoa miten ton hoitaa. Siellä on nakki info kokoelma instanssi, joka jaetaan näitten näkymien välillä, pitäisi varmaan bindata add tai change event siihen rendaukseen

**Comment by haivala** [comment]
tai vaihtaa vaan niiden elementtien järjestys jolloin loogisesti etekisi kaiken järjestyksessä https://github.com/EntropyRy/nakkikone/issues/29

**Comment by d4gg4d** [comment]
Järjestys vaihdettu, joten tämä ei oletettavasti tule olemaan kaksinen vaiva käyttäjälle. Teknisesti tämän korjaaminen tarkoittaisi sitä, että koko nakkitype_editor refaktoroitaisiin uuteen uskoon, koska nykyinen toteutus olettaa vahvasti siihen että noi ei muutu editointi moodissa, eli käyttäjä editoi yhtä asiaa kerrallaan.
