### ISSUE TITLE
Admin: Rakenteellinen muutos

### ISSUE THREAD

**Issue by haivala** [EntropyRy/nakkikone#29]
Mielestäni nämä kaikki voisivat olla samanlaisia elementtejä ja tässä järjestyksessä:
EDIT PARTY DETAILS
EDIT NAKKI TYPE DETAILS (on nyt nakki info details ja alempana)
EDIT NAKKI TIMETABLE (on nyt nakki table schema ja sisältyy partydetails elementin sisään.)
PARTY ORGANIZERS INFORMATION

Käytettävyys paranisi.. 
Yleensä kuitenkin tiedämme mitä nakkeja bileisiin tulee ennemminkuin että monelta ne alkaa tai loppuu

**Comment by d4gg4d** [comment]
Kyllä, tämä järjestely varmasti selventäisi tuota käyttö kokemusta

**Comment by d4gg4d** [comment]
https://github.com/EntropyRy/nakkikone/commit/a6a8e1b815b1f149cfa67192f52b8cf96f178563
