### ISSUE TITLE
ADMIN: "Update NakkiTable" -nappula

### ISSUE THREAD

**Issue by haivala** [EntropyRy/nakkikone#30]
Parasta olisi, että jos aikatauluun on tehty muutoksia, ko nappula muuttuisi joko punaiseksi tai vihreäksi

huomasin koska BUGI: 
paina "Create new type" valitse nakki ja ajat, niin sitä automaagisesti painaa uudestaan Create new type jolloin edellisen nakin tiedot nollautuu ja ne joutuu tekemään uudestaan.

**Comment by d4gg4d** [comment]
Kyllä, aiheuttaa pään vaivaa jotka eivät entuudestaan tiedä miten toi toimii. Noh, toiminnallisuus pitäisi uusia muutenkin tuon komponentin osalta

**Comment by haivala** [comment]
Nyt siinä lukee ainakin ohjeet asiaan

**Comment by d4gg4d** [comment]
Uudelleen srukturoitu, siten että delete ja create on samalla loogisella tasolla. Editointi tapahtuu normaalisti erillisessä näkymässä.

https://github.com/EntropyRy/nakkikone/releases/tag/2.7.2
