### ISSUE TITLE
ADMIN: Kahta saman nimistä nakkia ei voi olla aikataulussa

### ISSUE THREAD

**Issue by haivala** [EntropyRy/nakkikone#31]
Nyt kun nakkin nimen joutuu vaitsemaan niin helposti tekee 2 saman nimistä nakkia kerralla ja antaa niille eri ajat. (vai pitäisikö "Create New Type" laittaa piiloon aina ennen kuin on painanut update nakki table? eli luonut yhden nakkiaikataulun)

**Comment by d4gg4d** [comment]
Tämä pitäisi katsoa läpi, ainoastaan taulun parsiminen on asia missä tuo nakkityypin nimi rajoitus on tarpeellinen. Siitä voisi luopua jos ryhmittelyn taustalla tekee avaimilla.

**Comment by d4gg4d** [comment]
https://github.com/EntropyRy/nakkikone/releases/tag/2.5
