### ISSUE TITLE
Valinta "taking down/buiding up"

### ISSUE THREAD

**Issue by haivala** [EntropyRy/nakkikone#33]
Tuo select laatikko ei ole mikään paras tuohon.
Olisiko järkevämpää vaihtaa siihen checkboxit?
Nillä voisi myös näyttää että minkä on jo valinnut

**Comment by d4gg4d** [comment]
Vois olla ihan kelpo vaihto

**Comment by d4gg4d** [comment]
https://github.com/EntropyRy/nakkikone/releases/tag/2.6.1
