### ISSUE TITLE
ADMIN: Description kentän rendaus

### ISSUE THREAD

**Issue by haivala** [EntropyRy/nakkikone#34]
joko wysiwyg tai sitten niin että description kentän rendauksen näkee vain frontista. Nyt mahdollista rikkoa sivusto.

**Comment by d4gg4d** [comment]
Mikä se oli mitä sinä ehdotit?

**Comment by d4gg4d** [comment]
https://github.com/EntropyRy/nakkikone/issues/26

**Comment by d4gg4d** [comment]
http://jhollingworth.github.io/bootstrap-wysihtml5/

**Comment by d4gg4d** [comment]
https://github.com/EntropyRy/nakkikone/tree/2.6
