### ISSUE TITLE
Nakki tablen ajat väärin

### ISSUE THREAD

**Issue by haivala** [EntropyRy/nakkikone#35]
10:00	Take
11:00	Take
20:00	Take
21:00	Take
22:00	Take
12:00	Take
13:00	Take
14:00	Take
15:00	Take
16:00	Take
17:00	Take
18:00	Take
19:00

**Comment by d4gg4d** [comment]
Hyvinkin mahdollista että liittyy siihen että noi slotit sortataan Stringeinä eikä Integereinä, näyttäisi juurikin olevan 2000 10. slotti

**Comment by d4gg4d** [comment]
08b92d588f3ada84f4bf8f317f929b99766dcbf2
