### ISSUE TITLE
Update nakkitable nappula

### ISSUE THREAD

**Issue by haivala** [EntropyRy/nakkikone#36]
Sen pitää varottaa että taulu tyhjentyy jos siellä on jo varauksia.
Tai sitten sen pitäs vaan toimia että niitä voi editoida :D

**Comment by haivala** [comment]
tapahtu meinaan niin että taulu tyhjenty taas niin olis kiva semmonen oletko varma dialogi jos hommaa ei muuten korjata

**Comment by d4gg4d** [comment]
Editointi siten etta droppaa ne jotka jaa editoinnin ulkopuolelle? Hieman tyolaampi prokkis mahdollisesti.

**Comment by haivala** [comment]
tällähetkellä kaikki nakit resetoituu kun painaa ko. nappulaa. lisäsin tekstin tämän nappulan viereen, että niin käy. 
sidenote: nakkeja voi kuitenkin poistaa ja lisätä aikatauluun niin että ne vaikuttas muiden nakkin varauksiin. Ainut ongelma on siis nakkiaikataulun editointi.

**Comment by d4gg4d** [comment]
en tule muuttamaan, ei varsinaisesti bugi
