### ISSUE TITLE
Admin: Päivämäärän valinta ennen bileiden nimeä

### ISSUE THREAD

**Issue by haivala** [EntropyRy/nakkikone#39]
Nyt tuppaa frontissa olemaan tämmöisiä otsikoita:
"21.5.2016 Eetteri @ 21.05.2016, 22:00"
ei hyvä.

**Comment by d4gg4d** [comment]
Ehdotuksia paremmaksi :). Eihan tuo ole kuin templaatin muutos

**Comment by haivala** [comment]
näihän se on. pitänee nää silti laittaa ylös :)

**Comment by d4gg4d** [comment]
niin siis ideana etta ensin valitaan pvm? koska jengi tunkee sita pvm tuohon bileitten nimeen :smile: . Ok, pitaa varmaan vahan miettia tota bileitten nimen maaritysta.

**Comment by d4gg4d** [comment]
Oisko vaan parempi jos nimi maaritellaan siina editorissa niinkuin kaikki muutkin arvot? Se vois olla se ratkaisu tohon.

**Comment by haivala** [comment]
mitä jos se otsikko reviewataan livenä sille käyttäjälle?

**Comment by haivala** [comment]
jaahas. kun painaa new party tulee modali joka kysyy bileiden nimeä. lisäsin siihen siis tekstin että älä laita päivämäärää tähän kenttään ja vaihoin "title" sanan "name":ksi. Katotaan jos tuo riittäs
