### ISSUE TITLE
ADMIN: WYSIWYG editorin linkki nappula

### ISSUE THREAD

**Issue by haivala** [EntropyRy/nakkikone#42]
en pystynyt linkkaamaan entropy.fi bileiden postaukseen Eetteristä

**Comment by d4gg4d** [comment]
hmm, eli linkkien rakennus editorissa ei toiminut?

**Comment by haivala** [comment]
en muista tarkkaan, mutta olisko ollu https ongelma..

**Comment by d4gg4d** [comment]
toimii, suljen
