### ISSUE TITLE
Nakkivarauksen yliajo

### ISSUE THREAD

**Issue by haivala** [EntropyRy/nakkikone#43]
Jos 2 ihmistä lataaa sivun samaan aikaan ja toinen varaa nakit.
Toinen on vähän hitaampi mutta suorittaa samojen nakkien varauksen, niin se yliajaa edelliset varaukset.

**Comment by d4gg4d** [comment]
jeps, tiedetty "bugiloinen". Oletettavasti ensimmainen varaa ja toinen feilaa tassa casessa?

**Comment by haivala** [comment]
ei kun kummatkin varaa normaalisti (käsittääkseni virheitä ei ole tullut). toisen varaus vaan yliajaa esimmäisen varauksen eikä ensimmäinen tiedä siitä mitään

**Comment by d4gg4d** [comment]
teen niin etta ensimmaisen varauksen jalkeen varauksen voi ylikirjoittaa vain admin kayttaja.
