### ISSUE TITLE
Bileen disablointi

### ISSUE THREAD

**Issue by haivala** [EntropyRy/nakkikone#44]
-vanhat nakkikoneet vois disabloida ettei niitä pääsis enää kattomaan kuin admini.
-ne vois automaagisesti disabloitua 3 päivää bileiden jälkee
-luodessa ne on tietenkin enabled

**Comment by d4gg4d** [comment]
Tehdaan nopeesti, naytetaan 2 viikkoa ennen bileita ja piilotetaan 3 pv bileitten jalkeen, nopee temppu. Oisko riittava ominaisuus?

**Comment by d4gg4d** [comment]
laitetaan 4 viikkoa auki niin ei tarttee jannittaa.

**Comment by haivala** [comment]
eli 4 viikkoa auki ennen bilettä? ja 3pv auki bileen jälkee?
