### ISSUE TITLE
Yhden koneen URL

### ISSUE THREAD

**Issue by haivala** [EntropyRy/nakkikone#46]
Niitä bileet urleja vois kans hieman enforcettaa, jos poistan sen indeksi haun kokonaaan niin bileitten urli 
on sit se bileen nimi

Mitä jos samalle päivälle on monta konetta?

**Comment by d4gg4d** [comment]
Ei ole paivalla valia jos tullaan bile kohtaisella urlilla. jos tullaan geneerisella niin ottaa lahimman tulevaisuudessa.

**Comment by d4gg4d** [comment]
nykyisin toimii tammoisesta urlista https://nakkikone.entropy.fi/#party/id/<bileen-nimi>, esim https://nakkikone.entropy.fi/#party/id/Eetteri 

Mutta tuota voisi hoonata paremmaksi, se voisi olla vaikka

https://nakkikone.entropy.fi/#<bileen-nimi> ?

**Comment by haivala** [comment]
tarkoitin että jos samaan bileeseen on monta nakkikonetta jolloin sen nimi on sama ja päiväkin voi olla sama.. tämä siksi koska nakkitauluun ei mahdu leveys suunnassa mahdottoman monta nakkia, niin olisi helpompaa jakaa niitä moneen koneeseen.. tms (jos nyt ei keksitä tähän jotain muuta keinoa)

Olisko hyvä jos olis https://nakkikone.entropy.fi/id/nimi
eli https://nakkikone.entropy.fi/305/Eetteri
Käytännössä siis identifioidaan tuolla id:llä ja loppu on urli on nimi. Nimen funktio on vaan kaunistaa urlia eli sitä ei oikeesti tarvita. Tai miten nyt sitten on helppo toteuttaa

**Comment by d4gg4d** [comment]
Niin aattelin etta ois hyva nimi jos ois pelkastaan tuo bileen nimi se urli, ilman ulkomuistettavia Ideita. Tuo saman bileen jakaminen usealle nakkikoneelle onnistuu vain jos bileitten nimia jatkaa jollain numerolla tai muulla identifioivalla.

`https://nakkikone.entropy.fi/#Eetteri-1` ja 
`https://nakkikone.entropy.fi/#Eetteri-2` etc

Tassa on se rajoitus tallahetkella etta kahdella bileella ei voi olla samaa nimea, pitaisiko siita mielestasi luopua? Sen voi kylla purkaa sielta mutta sitten tulee mielenkiintoisia tulkinta kysymyksia kumpi bile tulisi nayttaa jos urli on tosiaan `https://nakkikone.entropy.fi/#Eetteri`

Mutta, tuohon etta on niin isot bileet etta vertikaali tila loppuu kesken pitais kehittaa joku päheempi raktaisu tuossa public ruudulla... Se ois se oikee ratkaisu, naa muut on hieman purkka ratkaisuja.

**Comment by haivala** [comment]
ok. laitetaan siis pelkkä nimi, niin on helppo muistaa

**Comment by d4gg4d** [comment]
tehty
