### ISSUE TITLE
Admin: ei näe vanhoja nakkikoneita

### ISSUE THREAD

**Issue by haivala** [EntropyRy/nakkikone#50]
esim KS 2015 voi valita navigaatiosta mutta Paviljonki ei toimi
Tämä siis frontissa. ei admin liittymässä.

**Comment by d4gg4d** [comment]
Näitä on useampia, ja näyttäsi johtuvan siitä että ko juhla ei löydy titlensä perusteella. Huomaan että erikoismerkit (`/`  ja `.`) otsikossa aiheuttavat hajoamisen.

**Comment by haivala** [comment]
jeps. Paviljongin linkissä on .

**Comment by d4gg4d** [comment]
korjaan taman siten etta kiellan nuo merkit bileitten otsikoissa. Dot on railsin rajoite, / tekee urleista todella hassuja
