### ISSUE TITLE
Nakkikoneen rekisteröitymisessä tiedot GET-parametreina

### ISSUE THREAD

**Issue by haivala** [EntropyRy/nakkikone#53]
Rekisteröitymisen jälkeen päädytään URLiin, jossa on kaikki lähetetyt tiedot. Ei ole hyvä välittää GET-parametreina esim salasanaa. Nuo kun päätyvät esim selaimen selaushistoriaan, web-palvelimen lokeihin, proxyihin jne. Parempi on lähettää tietoja aina POST-viestin rungossa.

**Comment by d4gg4d** [comment]
Tämä pitäisi olla kyllä POST kysely, onkohan siinä nyt käpy (javascript puoli).

Katso, https://github.com/EntropyRy/nakkikone/blob/master/app/assets/javascripts/components/submit-form.js
ja
http://backbonejs.org/#Model-save

**Comment by d4gg4d** [comment]
Millä selaimella sait toistettua?

**Comment by haivala** [comment]
Darkker kertonee lisäinfot, laitto postia webmasterille

**Comment by haivala** [comment]
tarkista tosiaan toi emaili

**Comment by d4gg4d** [comment]
korjattu.
